#+TITLE: YAJET -- JavaScript Emplate Tengine
#+STYLE: <link rel="stylesheet" type="text/css" href="docstyle.css" />

* Yet Another JavaScript Emplate Tengine[fn:name]

A “template engine” is a tool able to transform some text into another, by
interpreting/replacing various patterns in the source text.  YAJET is such a
tool designed for client-side (JavaScript, in-browser) transformation.

YAJET is a compiler, in the sense that it transforms your template into
runnable JavaScript code; after compiling a template you get a function
which you can call with data required to fill your template, and it returns
it rendered.

YAJET is appropriate for any kind of text templates -- it was not designed
specifically for HTML, although that's mostly what we use it for.

* What makes it different?

I'm hot happy with the syntax of various template tools.  Let's face it,
they're all creepy.  How many times have you seen stuff like this in PHP
code:

#+BEGIN_EXAMPLE
<?php if (...) { ?>

... two
... thousand
... lines
... here

<?php } ?>
#+END_EXAMPLE

At some point the code becomes write only: you have no clue what's going on
and where, you can't fix it, all you can do is add another IF.

The defining quality, I think, of YAJET is that, while it allows you to pass
literal JavaScript code[fn:literal-js], it doesn't allow you to pass
unbalanced structures.  In other words, it's impossible to start a literal
JS block in a part of the template and end it in some other part.

The syntax that I'm proposing encourages you to split your template into
small components and call them where appropriate; blocks should not become
very long in this way.  It shares some conceptual similarities with the
venerable [[http://template-toolkit.org/][Template::Toolkit]] (which is probably the best template engine I've
used so far) and some syntactic ones with Lisp.

Also see [[Correctness]].

* Features

Other than the boring variable replacement, YAJET supports the following
(and I will explain them all in this document):

- conditionals (=IF= / =WHEN= / =UNLESS=, =ELSE=, =ELSIF=).  =WHEN= is a
  synonym to =IF=, and =UNLESS= is, of course, the complete opposite.
  =ELSE= and =ELSIF= are supported both in =IF/WHEN= and in =UNLESS= blocks,
  but using =ELSE= in an =UNLESS= block makes the code look a bit werid.

- repetitive constructs (=REPEAT= / =LOOP=).  They allow you to repeat a
  part of the template a few times. =LOOP= is a synonym to =REPEAT=.

- iterating array or hashes (=MAP= and =MAPHASH=) -- =MAP= to traverse a
  list and =MAPHASH= to iterate an object (hash table).

- all loops can be controlled by =BREAK= or =CONTINUE=.

- variable definition (=LET=, =VAR= and =WITH=).  =LET= and =WITH= introduce
  new lexical scopes.

- components (=BLOCK= and =FUNCTION=).  Useful to declare a block that can
  be called as a function.  =BLOCK= will feed its output into the main
  output stream, while =FUNCTION= will return it.  Both are closures within
  their lexical context.

- components can be called using =WRAP=.  They receive some content and are
  able to output something before and after it.

- simple filters a la Template::Toolkit (i.e. =$foo|html= will HTML-escape
  the value of foo).

- it compiles the template into a runnable JavaScript function which is
  blazing fast.

- it does not use eval().

- the code is shorter than the documentation (~500 lines of code, 5.5K
  minified, 2.2K gzipped) and it's completely self-contained (no library
  requirements, and it should not clash with any library).

* Usage

You need to load [[../js/yajet.js][yajet.js]], and to create an instance like this:

#+BEGIN_EXAMPLE
var yajet = new YAJET({
    reader_char : "$",
    with_scope  : false,
    filters     : {
        foo: function(val) { ... },
        bar: function(val) { ... }
    }
});
#+END_EXAMPLE

All arguments are optional.  Then to compile a template, you do this:

#+BEGIN_EXAMPLE
var func = yajet.compile("You said: $this.foo $this.bar");
#+END_EXAMPLE

and to execute it:

#+BEGIN_EXAMPLE
alert( func({ foo: "hello", bar: "world!" }) );
#+END_EXAMPLE

** Template arguments

The function created by “yajet.compile” receives one argument, and that
argument is available in your templates via the JavaScript =this= keyword.
This is the default behavior, because I think it's the best one in general,
but if you don't like to use the =this.= prefix to access the members you
can pass =with_scope: true= in the constructor.  It wraps the generated
function in a =with(this) { ... }= block, so the above would become:

#+BEGIN_EXAMPLE
var yajet = new YAJET({ with_scope: true });
var func = yajet.compile("You said: $foo $bar");
// and call it the same way:
alert( func({ foo: "hello", bar: "world!" }) );
#+END_EXAMPLE

It's more convenient, but it's slower (more than 10 times slower sometimes).
How much slower depends on how big is your template and how many variables
there are.  If you want a performance benchmark with and without the =with=
statement, [[../test/with.html][see this file]] (Firebug is required for timing the operations;
watch the Firebug console; it also works in Chrome with its JavaScript
console; Chrome is even slower than Firefox for the =with= case).

** Reader char

Template syntax is triggered by a special “reader char”.  By default this
character is =$=, but you can use anything else by passing the =reader_char=
constructor argument.  I personally would prefer to use some Unicode
character, for instance:

#+BEGIN_EXAMPLE
var yajet = new YAJET({ reader_char: "•" });
var tmpl = yajet.compile("You said •foo •bar");
#+END_EXAMPLE

* Syntax

YAJET parses the template as text, leaving it unchanged, until it encounters
the “reader char”.  What follows in this document will assume that $ is the
reader character (the default).  A few types of constructs are recognized:

- =$$= --- inserts a literal $ character.

- =$-= --- kills the following whitespace.

- =$foo= --- inserts the value of the variable foo.

- =${ foo.bar.baz() }= --- evaluates the given JavaScript expression and
  inserts the return value, if any.

- =$(INSTRUCTION ... $)= --- processes the contents according to some rules
  which are particular for INSTRUCTION.

- =$( ... )= --- inserts literal JavaScript code (must not be ill-formed!).

** Simple interpolation (the =$foo= construct)

To insert a variable you can say =$foo=, =$foo.bar=, etc.  This case is
quite simple.  The parser will stop at a character which isn't a letter, a
digit, an underscore or a dollar sign.  Additionally it supports filtering
the values with a convenient syntax: =$foo|html=.

Filters are functions that take one argument and should return the modified
value.  You can easily define your own filters (but later on this).  Filters
can be combined, for example: =$foo|upcase|html= will first make foo
uppercase, then apply the html filter to the upcased string.

** JavaScript expressions (the =${exp}= construct)

This is similar to the “simple interpolation” case, but it allows for more
complicated expressions.  For example =${a+b}= will insert the sum of a and
b.  Your expression can be arbitrarily complex, and the scanner is smart
enough to read it, provided that it is valid JavaScript code (you need to be
*careful about literal RegExp-s* though, for now; I'll fix this in a later
release; more on this in [[Known issues]]).

So, an example of a perfectly valid call is:

#+BEGIN_EXAMPLE
${
   // Comments are allowed and can even contain the closing bracket: }
   // it's ignored, since it is in a comment.
   (function(arg){
     return arg.a + arg.b + arg.text;
   })({
     a: 5,
     b: 10,
     text: "(foo}"
   })
}
#+END_EXAMPLE

The expression is evaluated at runtime and its value is inserted into the
template output only if it's not null.

*** Filters

As already noted, the =$foo= construct allows filtering the value through
some function using a convenient syntax like =$foo|html=.  At the time of
this writing the filters available by default are:

- =html= --- encodes HTML special characters
- =upcase= --- converts the string to uppercase
- =downcase= --- lowercase the string
- =trim= --- removes leading and trailing whitespace

It's easy to define custom filters when you construct the YAJET object:

#+BEGIN_EXAMPLE
var yajet = new YAJET({
    filters: {
        md5: function(value) {
            return md5_hex_of(value); // return the modified value
        }
    }
});
#+END_EXAMPLE

... and in your template: =$password|md5=.

There is also a syntax that allows for filters within the =${exp}=
construct.  But since we parse valid JavaScript code, and since the pipe is
a valid JavaScript character (“bitwise or”), we have to use something
different.  The idea was, thus, that such expressions will be parsed as a
list; the first element of the list is the expression itself, and any
additional elements are filters.  For example:

#+BEGIN_EXAMPLE
${ this.getLabel(), upcase, html }
#+END_EXAMPLE

will convert into something like this:

#+BEGIN_EXAMPLE
output_string(
  apply_html_filter(
    apply_upcase_filter(
      this.getLabel()
    )
  )
)
#+END_EXAMPLE

Since the comma doesn't look very nice for this particular case, the “list
reader” also allows a few aliases.  Syntactic sugar, baby!  You can also
use:

- =“=>”=
- =“;”=
- =“..”=
- =“;”=
- =“IN”= (case insensitive, but /must/ be preceded by whitespace)

So the above example can also be written like this:

#+BEGIN_EXAMPLE
${ this.getLabel() IN upcase, html }
${ this.getLabel() => upcase => html }
${ this.getLabel() => upcase, html }
${ this.getLabel() .. upcase; html }
#+END_EXAMPLE

These special separators only work for the “list reader”, which is used in
the =${exp}=-like constructs (and several others).  Also, note that filters
are only interpreted in the top-level elements of this list, so for instance
the following won't apply the "html" filter to “foo”: =${ something(foo,
html) }=.  It will just call, instead, the function =something=, passing the
variables =foo= and =html=, which is expected behavior.

When used in the =${foo}= construct, filters can receive additional
arguments.  For example, assuming you have some date formatting library, you
can easily define a filter that formats a Date object according to the
arguments:

#+BEGIN_EXAMPLE
var yajet = new YAJET({
    filters: {
        format_date: function(date, format) {
            // ... now return the *date* formatted according to *format*
        }
    }
});

// and in the template:

“Today is: ${ new Date() => format_date("YYYY-MM-DD") }”
#+END_EXAMPLE

The first argument of your filter is always the value from the template (in
the above case, the Date object created with =new Date()=), and the other
arguments are passed following the filter name ("YYYY-MM-DD").

** Directives

So far we are able to introduce arbitrary JavaScript variables and
expressions in the template.  However that's hardly enough.  First off, the
expressions must be well-formed, so there is no way to start a JavaScript
block somewhere and end it some place else.  The following is invalid for
obvious reasons:

#+BEGIN_EXAMPLE
${ if (link != null) { }
  <a href="$link|html">$link</a>
${ } }
#+END_EXAMPLE

I emphasize that the lack of support for partial expressions is a /feature/,
not a limitation.  This will never be “fixed”.  To support constructs like
the above but without encouraging poorly written templates that start a
block on line 10 and end it on line 1000, we have a few special processing
directives.  Let's call these the =$(BAR ... $)= construct.  To start with,
here is how you would write the above code:

#+BEGIN_EXAMPLE
$(IF (link != null)
  <a href="$link|html">$link</a>
$)
#+END_EXAMPLE

Note that you still can start a block on one line and end it on another, but
the style is a bit different.  Instead of inserting arbitrary code
unconditionally, we simply end a known construct.  The condition that you
pass to WHEN must be fully valid JavaScript (you cannot pass a partial
expression there) and, if your editor does a good job about matching parens,
then you can quickly see where the block begins/ends by moving the cursor to
the parens.  I prefer this style.

Note that the processing instructions are not case-sensitive.  I prefer to
use UPPERCASE for them so that they stand out visually.

The =$(BAR ... $)= construct has the following properties:

- it starts with =$(= (so it's a normal paren, not a bracket).
- it continues with a special instruction (again, I prefer uppercase for
  this but it's not required).
- depending on the instruction, certain arguments may follow.
- it /should/ end with =$)=.
- it may contain a /block of text/ between the arguments and the =$)=
  terminator.

The /block of text/ is parsed normally, so it's interpreted as plain text
until =$= (the reader char) is encountered, then what follows the reader
char is processed by the rules I described in this document.

Following I will describe the directives available at this time.  I think
the set of them is quite comprehensive and allows you to express any kind of
template in a simple and consistent manner.

*** =IF= / =WHEN= / =UNLESS=, =ELSE= / =ELSIF= --- conditional execution

=IF= and =WHEN= are synonyms, while =UNLESS= is the antonym.  =WHEN= seems more
appropriate for cases where you don't have an =ELSE= clause.  They support one
argument which must be a condition enclosed in parens.  Examples:

#+BEGIN_EXAMPLE
$(WHEN (user_id == null)
  <a href="...">Please login</a> $)

$(UNLESS (user_id != null)
  <a href="...">Please login</a> $)

$(IF (a < b)
  <p>A is smaller</p>
$(ELSIF (a > b))
  <p>B is smaller</p>
$(ELSE)
  <p>A and B are equal</p> $)
#+END_EXAMPLE

Note that you can use =ELSE= or =ELSIF= inside =UNLESS= or =WHEN= blocks
too, although I would not advise to use this style:

#+BEGIN_EXAMPLE
$(UNLESS (a == b)
  they are different
$(ELSE)
  they are equal $)
#+END_EXAMPLE

You should also note that =ELSE= and =ELSIF= are not actually parsed like
other instructions.  They don't take a block of text, and thus they don't
need to end with =$)=.  Whether to do it this way was hard to decide, but
since =ELSE= and =ELSIF= normally /continue/ an IF block, instead of ending
it, it seems to make sense this way.  The same applies to =$(BREAK)= and
=$(CONTINUE)= directives.

*** =REPEAT= / =LOOP= --- to repeat stuff

To repeat a part of the template you can use =REPEAT= or =LOOP= (they are
synonyms).  For example, the following outputs “foo” 3 times: =$(REPEAT (3)
foo $)=.  In various cases you might need to know the current iteration too,
so you can pass a variable name for it:

#+BEGIN_EXAMPLE
$(REPEAT (5, i)
  Item $i $)
#+END_EXAMPLE

The variable =i= takes values from 1 to 5 (inclusively) and the output will
be “Item 1 Item 2 ” etc.  In some cases you might want to specify an
interval (so that you start from something else than 1), so the following is
allowed:

#+BEGIN_EXAMPLE
$(LOOP (5 .. 10 => i)
  <a href="/page$i">Page $i</a> $)
#+END_EXAMPLE

The =LOOP= keyword seems to be nicer in this case, but again, they are
synonyms.  Also note that the arguments are parsed using the “list reader”,
so you can use syntactic sugar to separate them (although a simple comma
would do).

*** =MAP= / =FOREACH= --- iterate an array

Again, =MAP= and =FOREACH= are synonyms.  You can use them to do something
for each element of an array.  For example the following outputs links
contained in an array:

#+BEGIN_EXAMPLE
$(MAP (link => links)
  <a href="$link.address|html"
     title="$link.tooltip|html">$link.text|html</a> $)
#+END_EXAMPLE

That's assuming that =links= is an array of objects, each containing
=address=, =tooltip= and =text=.  You could also use a literal object (the
parser is smart enough for this):

#+BEGIN_EXAMPLE
$(MAP (link => [ { address : "http://www.google.com/",
                   tooltip : "Search engine",
                   text    : "Google" },

                 { address : "http://www.ymacs.org/",
                   tooltip : "AJAX code editor",
                   text    : "Ymacs" }
               ])
  <a href="$link.address|html"
     title="$link.tooltip|html">$link.text|html</a> $)
#+END_EXAMPLE

Sometimes you also need to know the current step of the iteration.  For
example if you want to output some links that are separated with a pipe, you
need to know not to output the pipe before the first, or after the last
link.  We could write it like this:

#+BEGIN_EXAMPLE
$(MAP (i, link => links)
  $(WHEN (i > 0) | $)
  <a href="$link.address|html"
     title="$link.tooltip|html">$link.text|html</a> $)
#+END_EXAMPLE

or

#+BEGIN_EXAMPLE
$(MAP (i, link => links)
  ${ i > 0 ? "|" : "" }
  <a href="$link.address|html"
     title="$link.tooltip|html">$link.text|html</a> $)
#+END_EXAMPLE

A special case of =MAP= / =FOREACH= allows you to pass only the array, and
no key or index variables.  In this case the special variable =$_= (which I
will call the Perlism) gets assigned to the current element, and /more/, the
loop body is lexically scoped to each element using a JavaScript =with=
block (I know, your mom told you not to play the =with= statement, but mine
didn't[fn:with] :-p).

So using this style the first example would become:

#+BEGIN_EXAMPLE
$(MAP (links)
  <a href="$address|html" title="$tooltip|html">$text|html</a> $)
#+END_EXAMPLE

=address=, =tooltip= and =text= access the specific property of each
element.

Just a last example showing the Perlism:

#+BEGIN_EXAMPLE
$(FOREACH ([ "foo", "bar", "baz" ]) <b>$_</b> $)
#+END_EXAMPLE

will output “<b>foo</b> <b>bar</b> <b>baz</b>”.  The =$_= variable is bound
to each element.

*** =MAPHASH= --- iterate an object (hash)

=MAPHASH= is =MAP='s analogue for hashes.  It iterates over all properties
of an object, binding a variable for the key and another for the value.  You
must specify names for these variables.  Example, assuming that =users= is a
hash that maps user IDs to some user objects (each of them having a
=getName()= method):

#+BEGIN_EXAMPLE
$(MAPHASH (uid, obj => users)
  User <b>$uid</b> has name <b>${ obj.getName() }</b><br /> $)
#+END_EXAMPLE

*** =CONTINUE= and =BREAK= --- for loop control

These don't take any arguments, and also don't take a block of text, so the
expected syntax is =$(CONTINUE)= and =$(BREAK)=.  They can appear in the
text block of some looping construct, be it =REPEAT=, =LOOP=, =MAP=,
=FOREACH= or =MAPHASH=, and they do the same as their JavaScript
counterparts, that is: =CONTINUE= will go to the next iteration, skipping
any code between it and the end of the loop, and =BREAK= will immediately
end the loop.

I'm giving an example just to illustrate the syntax:

#+BEGIN_EXAMPLE
$(REPEAT (10 => i)
  $(WHEN (i > 5) $(BREAK) $)
  $i
$)
#+END_EXAMPLE

The above will print numbers from 1 to 5.

*** =LET= and =VAR= --- define variables

You can define new variables with =LET= and =VAR=.  They are not equivalent:
=LET= introduces a new lexical scope, so the variables that you define are
only available in its block of text.  =VAR= on the other hand does something
similar to the standard JavaScript =var= keyword.  Note that they are /still
not global variables/---they are local to the innermost function that
contains the declaration, which in many cases is your template itself, but
could be a [[reusable template blocks][=BLOCK= or =FUNCTION=]] block too.

=VAR= does not accept a text argument, so it ends directly with a closing
paren (no need for =$)=).  Example:

#+BEGIN_EXAMPLE
$(VAR ((a => 10) (b => 20)))
$a + $b = ${ a + b }
#+END_EXAMPLE

If variables with the same name were previously defined, they are replaced
with the new ones.

=LET= introduces variables that are local to its block.  If variables with
the same name already exist, they are shadowed while the =LET= block is
rendered.  After the =LET= block ends, previous values come back to life.

#+BEGIN_EXAMPLE
$(LET ((a => 10) (b => 20))
  $a + $b = ${ a + b }
$)
#+END_EXAMPLE

Since =LET= takes a block of text, it ends with the normal block terminator
=$)=.  Here's an example to demonstrate scope:

#+BEGIN_EXAMPLE
$(VAR ((x => "outside")))
$(LET ((x => 10))
  $x is 10
  $(LET ((x => 20))
    $x is 20
  $)
  $x is back 10
$)
$x is "outside"
#+END_EXAMPLE

=LET= operates by introducing an anonymous function, so it is compatible
with all browsers.  JavaScript 1.7 introduced a =let= statement for
declaring block-scoped variables, and it's supported by Firefox, but
unfortunately no other browser has it at the moment.

*** =WITH= --- modify the scope chain

When you have an object that has properties you need to access, you can use
a =WITH= block to make for a more convenient syntax, so instead of saying
=$object.foo= you would be able to say only =$foo=.  Assuming that =link=
contains =address=, =tooltip= and =text=, the following two are equivalent:

#+BEGIN_EXAMPLE
<a href="$link.address|html" title="$link.tooltip|html">$link.text|html</a>

$(WITH (link)
  <a href="$address|html" title="$tooltip|html">$text|html</a> $)
#+END_EXAMPLE

=WITH= can be used with literal objects as well:

#+BEGIN_EXAMPLE
$(WITH ({ foo: 10, bar: 20 })
  $foo + $bar = ${ foo + bar }
$)
#+END_EXAMPLE

thus emulating a =LET= block, but it's less efficient because it uses the
[[https://developer.mozilla.org/en/Core_JavaScript_1.5_Reference/Statements/with][JavaScript with statement]].

*** =BLOCK= and =FUNCTION= --- define reusable template blocks

Both of these constructs define a function (local to your template) which
renders a text block.  The difference between them is that =BLOCK= will
define a function that “prints” the text block into the template output (and
returns nothing), while =FUNCTION= will just return it.

The syntax is straightforward.  They expect a name for the function,
followed by a list of arguments in parens (if there are no arguments, put
=()= like you do for a plain JavaScript function).  Then continue with the
block of text that the function should expand into:

#+BEGIN_EXAMPLE
$(BLOCK display_link(link)
  <a href="$link.address|html" title="$link.title|html">$link.text|html</a>
$)

<!-- call it literally -->
$( display_link({ address: "/", title="Home page", text: "Home" }) )

<!-- or call it for an object -->
$(FOREACH (i IN links)
  $( display_link(i) )
$)
#+END_EXAMPLE

As you see, using =BLOCK / FUNCTION= you can split your template into small
components.  Instead of having a big =FOREACH= loop that outputs a lot of
stuff, we can separate logical parts in blocks and then just call them, so
the loop itself becomes small.

Combining =BLOCK= and =LET= or =WITH= we can define closures:

#+BEGIN_EXAMPLE
$(WITH ({ value: 0 })
  $(BLOCK counter()
    <p>Counter is ${ ++value }</p> $) $)

$( counter() ) -- now it's 1
$( counter() ) -- now it's 2
$( counter() ) -- now it's 3
#+END_EXAMPLE

Doing the above with =LET= is a bit more tricky because =LET= creates its
own environment, so the =BLOCK= that you define within it is actually local
to the =LET= block.  The following won't work:

#+BEGIN_EXAMPLE
$(LET ((value => 0))
  $(BLOCK counter()
    <p>Counter is ${ ++value }</p> $) $)

$( counter() ) -- error, counter is not defined!
#+END_EXAMPLE

It's easy to see why if you see the code that gets generated for the above.
It looks like the following:

#+BEGIN_EXAMPLE
(function(){
    var value = 0;
    function counter() {
        output("Counter is " + (++value));
    };
})();

counter(); // but there's no free lunch
#+END_EXAMPLE

To do this with a =LET= block we would have to export the function; we can
use an outside variable for that:

#+BEGIN_EXAMPLE
$(VAR (counter))
$(LET ((value => 0))
  $( counter = _counter /* export it */ )
  $(BLOCK _counter()
    <p>Counter is ${ ++value }</p> $) $)

$( counter() ) -- now it works.
#+END_EXAMPLE

*** =WRAP=, =CONTENT= --- call a wrapper with an additional block of text

=BLOCK= can be used to define wrappers.  A wrapper is a function that
receives a bit of text and puts something before and after it.  For example,
to define a wrapper that creates a table we can say:

#+BEGIN_EXAMPLE
<!-- define our wrapper -->
$(BLOCK table(cols)
  <table>
    <thead>
      <tr>
        $(MAP (label => cols) <td>$label</td> $)
      </tr>
    </thead>
    <tbody>
      $(CONTENT)
    </tbody>
  </table> $)

<!-- and here's how we use it -->
$(WRAP table([ "Name", "Phone", "Email" ])
  <tr> <td>Foo</td> <td>123-1234</td> <td>foo@foo.com</td> </tr>
  <tr> <td>Bar</td> <td>1234-123</td> <td>bar@bar.com</td> </tr>
$)
#+END_EXAMPLE

You can note that a wrapper is a normal function defined with =BLOCK= or
=FUNCTION=, and it can take arguments.  To send the arguments with a =WRAP=
block, just make it look like a normal function call.  If there are no
arguments, you still need to insert the parens =()=.  When it's calling your
block, =WRAP= sends an additional hidden argument that contains the text
which is expanded by =$(CONTENT)=.  For now this argument is a function that
renders the text, and =$(CONTENT)= simply calls this function.

# <<Correctness>>
* Correctness

YAJET aims to do The Right Thing.  If you've ever written Lisp or C macros,
then you know that it's dangerous to invent variable names, or to use a
macro argument more than once.  YAJET is essentially a macro expander and
it's built around good principles.

For example, a dumb implementation would translate =$(FOREACH (link => links)
...STUFF... $)= into this:

#+BEGIN_EXAMPLE
for (var i = 0; i < links.length; ++i) {
    var link = links[i];
    ... do STUFF
}
#+END_EXAMPLE

However the above code has two problems:

1. if the text in =STUFF= defines a variable named =i=, then it will collide
   with the loop variable.

2. if =links= is not a real array, but say, a (possibly expensive, and
   perhaps with weird side effects) function call that returns an array,
   then it will be evaluated for each iteration... twice.

If =FOREACH= would really expand into the above code, then the following
sample would suffer from both problems:

#+BEGIN_EXAMPLE
$(FOREACH (link => this.getLinksFromServer())
  $(VAR ((i => link.text.length)))
  $(WHEN (i > 30)
    ... truncate text
  $)
  ...
$)
#+END_EXAMPLE

The resulted code would be:

#+BEGIN_EXAMPLE
for (var i = 0; i < this.getLinksFromServer().length; ++i) {
    var link = this.getLinksFromServer()[i];
    var i = link.text.length;
    if (i > 30) {
        ... truncate text
    }
    ...
}
#+END_EXAMPLE

... which means that this.getLinksFromServer() will be called twice for each
step, and also that the loop would be stopped arbitrarily when we encounter
a link whose text has more characters than the number of links.  That would
break in unexpected and hard to debug ways.

YAJET avoids this problem by creating temporary variables with (hopefully)
unique names, so that template writes don't have to worry about it.  The
actual generated code is more like this:

#+BEGIN_EXAMPLE
var __GSY12 = this.getLinksFromServer();
for (var __GSY13 = 0; __GSY13 < __GSY12.length; ++__GSY13) {
    var link = __GSY12[__GSY13];
    var i = link.text.length;
    if (i > 30) {
        ... truncate text
    }
    ...
}
#+END_EXAMPLE

The variables that are created get the prefix =__GSY= and a number which is
unique per compilation, so you should be safe as long as you don't use the
=__GSY= prefix yourself.  Hope you don't. :-)








* Known issues

** Literal RegExp-s in JavaScript expressions

The JavaScript parser is not “complete”, although it's smart enough to skip
comments and strings while looking for a closing paren.  Literal regexps are
always tricky to parse, so I left this out for now, but I do plan to fix it.
However, what this means for now is that you should be careful about parens
in literal RegExp-s.  Since the parser does not allow for unbalanced parens,
the following should /not/ be a problem:

#+BEGIN_EXAMPLE
$( if (/(a|b)/.test("bar")) {
     matches();
   } else {
     no_match();
   }
 )
#+END_EXAMPLE

All parens are properly closed, so there's no reason why our parser should
miss the closing paren.  However, the following will break stuff:

#+BEGIN_EXAMPLE
$( if (/\)/.test(")")) { ... } )
#+END_EXAMPLE

Although it is valid JavaScript inside, having the closing paren in the
RegExp will confuse YAJET.  It looks quite ugly, too---for such cases,
encode the paren as =\x29=.  Note that you have to escape open parens as
well (=\x28=), and same goes for all the other types of brackets such as
=[=, =]=,  ={= and =}=.

** Error reporting is less than ideal

** Whitespace handling




* License

Copyright (c) 2010, Mihai Bazon <mihai.bazon@gmail.com>.  All rights
reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.

    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER “AS IS” AND ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO
EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY DIRECT, INDIRECT,
INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.






#---- footnotes

[fn:literal-js] Although the directives that YAJET supports should provide
enough abstraction so that you don't need to pass on literal JS too often.

[fn:name] The misspelling is intentional.  Various combinations of the
letters Y, A, J, T, E from “Yet Another JavaScript Template Engine” led to
the name YAJET.  YAJET stands for “Yet Another JavaScript Emplate Tengine”.
Sounds buzzy, isn't it?  Also, [[http://en.wikipedia.org/wiki/Jet_engine][JET]]-s are fast, and so is YAJET.

[fn:with] Seriously though, everything under an =with= block is
s...l...o...w... -- so, while this makes for a nice syntax, you should not
use it where speed is critical.
